<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVjndapt\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVjndapt/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVjndapt.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVjndapt\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerVjndapt\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Vjndapt',
    'container.build_id' => '26d24691',
    'container.build_time' => 1523992617,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerVjndapt');
